Map<String, String> enLang = {
  'app_name' : 'Good To Grab',
  'intro_title' : 'Save Food, Save Money, Save the Environment.',
  'intro_subtitle' : 'Hey, Sustainable Hero! Let\'s start rescuing food here and make every meal count.',
  'Log in' : 'Log in',
  'dont have an account yet' : 'You Don\'t have an account yet',
  'Please' : 'Please',
  'Sign up Now' : 'Sign up Now',
  'agree_title' : 'By clicking on Login or Sign up, you agree to our',
  'Terms of Service' : 'Terms of Service',
  'Privacy Policy' : 'Privacy Policy',
  'and' : 'and',
  'SKIP' : 'SKIP',
  'signup_title' : 'Please enter your mobile number and full name',
  'login_title' : 'Please enter your mobile number',
  'Sign up' : 'Sign up',
  'Mobile Number' : 'Mobile Number',
  'Full Name' : 'Full Name',
  'Continue' : 'Continue',
  'OTP Verification' : 'OTP Verification',
  'We have sent a verification code to' : 'We have sent a verification code to',
  'Resend code' : 'Resend code',
  'Verify' : 'Verify',
  'Allow these permissions' : 'Allow these permissions',
  'Location' : 'Location',
  'location_permission_subtitle' : 'We will get your location city and we will get a list of nearby restaurants and cafes that can provide you with food in magic bags.',
  'Notification' : 'Notification',
  'notification_permission_subtitle' : 'Get push notifications for everything you need to know about exciting new stores, delicious foods, and more!',
  'Allow Permission' : 'Allow Permission',
  'Allow Location' : 'Allow Location',
  'Not Now' : 'Not Now',
  'Home' : 'Home',
  'Map' : 'Map',
  'Orders' : 'Orders',
  'Favourites' : 'Favourites',
  'Me' : 'Me',
  'Registered First' : " App doesn't have your mobile number registered yet. Please register your account before proceeding.",
  'Your location' : 'Your location',
  'Search restaurants and cafe' : 'Search restaurants and cafe\'s',
  'Enter Location Manually' : 'Enter Location Manually',
  'left' : 'left',
  'sold_out' : 'We\'re "SOLD OUT" for now. Please check later for updates.',
  'Total Magic Bags' : 'Total Magic Bags',
  'Add Location' : 'Add Location',
  'Search location' : 'Search location',
  'Use my current location' : 'Use my current location',
  'Filters' : 'Filters',
  'Food Type' : 'Food Type',
  'Food Preferences' : 'Food Preferences',
  'Veg' : 'Veg',
  'Non-veg' : 'Non-veg',
  'Pickup Distance' : 'Pickup Distance',
  'Pick-up Day' : 'Pick-up Day',
  'Today' : 'Today',
  'Tomorrow' : 'Tomorrow',
  'Pick-up window' : 'Pick-up window',
  'Clear all' : 'Clear all',
  'Apply' : 'Apply',
  'Magic Bag' : 'Magic Bag',
  'Next' : 'Next',
  'View Map' : 'View Map',
  'Pickup' : 'Pickup',
  'Select Pickup Day' : 'Select Pickup Day',
  'View Cart' : 'View Cart',
  'Your Orders' : 'Your Orders',
  'Profile' : 'Profile',
  'Money Saved' : 'Money Saved',
  'CO2e Saved' : 'CO2e Saved',
  'Edit' : 'Edit',
  'Payment Method' : 'Payment Method',
  'Help Center' : 'Help Center',
  'About us' : 'About us',
  'Contact us' : 'Contact us',
  'Enjoy App! Rate us' : 'Enjoy App! Rate us',
  'Log out' : 'Log out',
  'Delete Account Permanently' : 'Delete Account',
  'Call' : 'Call',
  'Email' : 'Email',
  'us' : 'us',
  'Edit Profile' : 'Edit Profile',
  'Save your First Magic Bag' : 'Save your First Magic Bag',
  'Change' : 'Change',
  'Add' : 'Add',
  'Save' : 'Save',
  'Upload profile picture' : 'Upload profile picture',
  'Account Login with'  : 'Account Login with',
  'Add favorites' : 'Add favorites',
  'Order Details' : 'Order Details',
  'Order Status' : 'Order Status',
  'Order ID'  : 'Order ID',
  'pickup_note' : 'Confirm and pick up your order with your order ID.',
  'Bill Details'  : 'Bill Details',
  'Subtotal' : 'Subtotal',
  'GST' : 'GST',
  'Platform Fee' : 'Platform Fee',
  'Total Pay' : 'Total Pay',
  'Restaurant Details' : 'Restaurant Details',
  'Order Cancel' : 'Order Cancel',
  'Payment'  : 'Payment',
  'choose_reason' : 'Choose a reason why this order has been canceled',
  'Camera' : 'Camera',
  'Gallery' : 'Gallery',
  'logout_subtitle' : 'Do you really want to log this device out?',
  'Cancel' : 'Cancel',
  'Yes' : 'Yes',
  'delete_account_subtitle' : 'Do you really want to delete this account permanently? If you delete your account, you lose all orders, payment methods, etc.',
  'Delete' : 'Delete',
  'Cancelled order successfully' : 'Cancelled order successfully',
  'cancelled_order_refund' : 'Your request will be reviewed and the amount will be credited to your account within 1-2 business days.',
  'Got It' : 'Got It!',
  'Total Money Saved' : 'Total Money Saved',
  'Magical Bag Saved' : 'Magical Bag Saved',
  'Original Value' : 'Original Value',
  'You Paid' : 'You Paid',
  'EQUICALENCE IN SAVED CO2e' : 'EQUICALENCE IN SAVED CO2e',
  'co2_subtitle' : 'Here\'s what your saved CO2e equals to',
  'Electricity' : 'Electricity',
  'Full Smartphone Charges' : 'Full Smartphone Charges',
  'Cups of hot Coffee' : 'Cups of hot Coffee',
  'time_to_hot' : 'Time to hot showering, heated by an electric boiler, 10-min electric boiler shower uses 2-3 KWh.',
  'Save your First Magical Bag' : 'Save your First Magical Bag',
  'Change Mobile Number' : 'Change Mobile Number',
  'Notifications' : 'Notifications',
  'Cart' : 'Cart',
  'Cart Details' : 'Cart Details',
  "search_country_name":"Search Country Name",
  "back":"Back",
  "login_subtitle" : 'Once you log in to Good To Grab, you will have access to all the features.',
  // exception
  'no_internet_connection' : 'Oops! No Internet Connection',
  'no_res_title' : 'No place here, yet!',
  'no_res_details_title' : 'Details are not available',
  'no_res_subtitle' : 'We\'re expanding Good To Grab as fast as we can, but it looks like we haven\'t made it to your neighborhood yet!',
  'no_fav_title' : 'There are no favorites yet!',
  'no_fav_subtitle' : 'check out some nearby places and tap on the ''favorite'' button- you will then get a notification when they have items available!',
  'no_orders_title' : 'Looking a bit empty here',
  'no_orders_subtitle' : 'Let\'s find a magical bag for you to save!',
  'no_magical_title' : 'Looking a bit empty here?',
  'no_magical_subtitle' : 'Let\'s find a magical bag for you to save!',
  "no_country_found":"No Country Found",
  "connection_timeout_exception":"Connection TimeOut",
  "something_went_wrong":"Something Went Wrong",
  "no_data_found" : "Unfortunately, no data was found",
  "no_place_here" : "No Place here, Yet!",
  "we_expanding" : "We\'re expanding Good To Grab as fast as we can, but it looks like we haven\'t made it to your neighborhood yet!",
  // firebase exception
  'firebase_invalid_phone_number' : 'The format of the phone number provided is incorrect',
  'firebase_too_many_request' : 'We have blocked all requests from this device due to unusual activity. Try again later',
  'firebase_invalid_code' : 'The sms code has invalid.',
  'firebase_session_expired' : 'The sms code has expired. Please re-send the verification code',

};
